{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(jwt_pizza_service_serviceTime{source=\"jwt-pizza-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful VS Failed Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_auth{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "title": "Orders Succeeded VS Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_orderAmount{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jwt_pizza_service_activeUsers{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "jwt_pizza_service_timeToOrder{source=\"jwt-pizza-service\"}",
     "legendFormat": "Time to order pizza"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_revenue{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas Ordered Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_numberOfPizzas{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizzas per minute"
    }
   ]
  },
  {
   "title": "Rate of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(jwt_pizza_service_requests{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jwt_pizza_service_CPU{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "jwt_pizza_service_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}